// 営業研修 修了テスト データ（100問）
// 選択肢は全て同程度の文字数に統一
// 難易度: basic(基礎), intermediate(標準), advanced(応用・深掘り読み物)

export interface FinalExamQuestion {
  id: number
  question: string
  options: string[]
  correctAnswer: number
  explanation: string
  source: string
  difficulty: "basic" | "intermediate" | "advanced"
}

export interface FinalExam {
  totalQuestions: number
  passingScore: number
  timeLimit: number
  questions: FinalExamQuestion[]
}

export const finalExamData: FinalExam = {
  totalQuestions: 100,
  passingScore: 90,
  timeLimit: 30,
  questions: [
    // ========================================
    // カテゴリA: 基礎マインドセット（17問）
    // ========================================
    {
      id: 1,
      question: "営業の本質として最も適切な定義はどれか？",
      options: [
        "自社製品を多くの顧客に販売する活動",
        "顧客の課題を発見し解決策を提案する活動",
        "競合他社との価格競争に勝つための活動",
        "売上目標を達成するための数字管理活動",
      ],
      correctAnswer: 1,
      explanation: "営業は単なる販売ではなく、顧客の課題を理解し解決策を提案する問題解決活動です。",
      source: "A: 基礎マインドセット - 研修1",
      difficulty: "basic",
    },
    {
      id: 2,
      question: "SPIN話法の「示唆質問」の主な目的は何か？",
      options: [
        "顧客の基本情報を収集するための質問",
        "問題を放置した影響に気づかせる質問",
        "自社製品の優位性を伝えるための質問",
        "顧客の購買意欲を直接確認する質問",
      ],
      correctAnswer: 1,
      explanation: "示唆質問は問題を放置した場合の影響を考えさせ、顧客自身が課題の大きさに気づくことを促します。",
      source: "A: 基礎マインドセット - 研修1",
      difficulty: "intermediate",
    },
    {
      id: 3,
      question: "顧客が「特に困っていない」と言った時の対応は？",
      options: [
        "次の機会を待って一旦引き下がる対応",
        "質問で潜在的な課題を引き出す対応",
        "他社事例を紹介して必要性を訴える対応",
        "価格メリットを強調して興味を引く対応",
      ],
      correctAnswer: 1,
      explanation: "顧客は自分の課題に気づいていないことがあります。質問を通じて潜在ニーズを顕在化させます。",
      source: "A: 基礎マインドセット - 研修1",
      difficulty: "basic",
    },
    {
      id: 4,
      question: "信頼構築フェーズを最初に行う理由として正しいのは？",
      options: [
        "効率的に商談を進めるための時間短縮策",
        "信頼がなければ本当の課題を話さないため",
        "競合他社との差別化を図るためのテクニック",
        "会社のルールとして決められているため",
      ],
      correctAnswer: 1,
      explanation: "信頼関係がなければ顧客は本当の課題を話しません。信頼構築が全ての基盤になります。",
      source: "A: 基礎マインドセット - 研修1",
      difficulty: "basic",
    },
    {
      id: 5,
      question: "「売れる営業」と「売れない営業」の決定的な違いは？",
      options: [
        "話術の巧みさと説得力の高さにある",
        "顧客視点で考え行動できるかどうか",
        "訪問回数と活動量の多さにある",
        "商品知識の深さと専門性にある",
      ],
      correctAnswer: 1,
      explanation: "トップ営業は顧客視点で考え行動します。自分本位ではなく顧客本位の姿勢が成果を生みます。",
      source: "A: 基礎マインドセット - 研修2",
      difficulty: "basic",
    },
    {
      id: 6,
      question: "初回商談での理想的なヒアリングと提案の比率は？",
      options: [
        "ヒアリング3割、提案7割が効率的である",
        "ヒアリング7割、提案3割が効果的である",
        "ヒアリング5割、提案5割がバランス良い",
        "状況次第で比率を変えるのが正解である",
      ],
      correctAnswer: 1,
      explanation: "初回商談ではヒアリング7割、提案3割が推奨されます。顧客理解が提案の質を決めます。",
      source: "A: 基礎マインドセット - 研修2",
      difficulty: "intermediate",
    },
    {
      id: 7,
      question: "営業における「準備8割」の考え方で正しいのは？",
      options: [
        "準備に時間をかけすぎず即行動すべき",
        "徹底した準備が商談の成否を決める",
        "準備より経験から学ぶ方が重要である",
        "準備は最低限にして数をこなすべき",
      ],
      correctAnswer: 1,
      explanation: "営業成果の8割は準備で決まります。顧客研究、想定問答、資料準備を徹底することが重要です。",
      source: "A: 基礎マインドセット - 研修3",
      difficulty: "basic",
    },
    {
      id: 8,
      question: "顧客の「検討します」という返答への最適な対応は？",
      options: [
        "わかりました、と引き下がり連絡を待つ",
        "検討のポイントや懸念点を具体的に確認",
        "期間限定の特別価格を提示して急かす",
        "上司を同行させて再度訪問のアポを取る",
      ],
      correctAnswer: 1,
      explanation: "「検討します」の裏には懸念や疑問があります。具体的に確認して次のステップにつなげます。",
      source: "A: 基礎マインドセット - 研修4",
      difficulty: "intermediate",
    },
    {
      id: 9,
      question: "心理学の「返報性の原理」を営業で活用する方法は？",
      options: [
        "高額商品を提案してから値引きを行う",
        "先に価値ある情報提供で信頼を構築",
        "競合の悪い評判を伝えて不安を煽る",
        "購入特典を多く付けて得した気にさせる",
      ],
      correctAnswer: 1,
      explanation: "返報性の原理では、先に価値を提供すると相手も返したくなります。情報提供が信頼構築につながります。",
      source: "A: 基礎マインドセット - 深掘り読み物",
      difficulty: "advanced",
    },
    {
      id: 10,
      question: "「アンカリング効果」の営業での正しい活用法は？",
      options: [
        "最初に低価格を提示してから値上げする",
        "最初に高い選択肢を見せて基準を作る",
        "競合の高い価格を引き合いに出して比較",
        "過去の取引価格を基準に交渉を進める",
      ],
      correctAnswer: 1,
      explanation: "最初に提示された情報が判断基準になります。プレミアムプランを先に見せることで選択を誘導できます。",
      source: "A: 基礎マインドセット - 深掘り読み物",
      difficulty: "advanced",
    },
    {
      id: 11,
      question: "営業で「社会的証明」を活用する効果的な方法は？",
      options: [
        "有名企業の導入実績を積極的に紹介する",
        "SNSのフォロワー数をアピールする",
        "業界紙への掲載記事を見せて説明する",
        "自社の売上ランキングを提示して説明",
      ],
      correctAnswer: 0,
      explanation: "「他の人も使っている」という情報は購買を後押しします。同業他社の導入実績が効果的です。",
      source: "A: 基礎マインドセット - 深掘り読み物",
      difficulty: "advanced",
    },
    {
      id: 12,
      question: "「損失回避バイアス」を営業で活用する方法は？",
      options: [
        "導入しないことで得られる利益を説明",
        "導入しないことで生じる損失を説明",
        "導入による直接的なコスト削減を説明",
        "導入企業の成功事例を詳しく説明する",
      ],
      correctAnswer: 1,
      explanation: "人は得ることより失うことを強く避けます。導入しない場合の機会損失を伝えることが効果的です。",
      source: "A: 基礎マインドセット - 深掘り読み物",
      difficulty: "advanced",
    },
    {
      id: 13,
      question: "営業の「ゴールデンサークル理論」でまず伝えるべきは？",
      options: [
        "What：何を売っているかの商品説明",
        "Why：なぜこの事業をしているかの理念",
        "How：どのように価値を提供するかの方法",
        "Who：誰がこのサービスを使うかの対象",
      ],
      correctAnswer: 1,
      explanation: "サイモン・シネックの理論では「Why」から始めることで共感を生み、強い動機付けができます。",
      source: "A: 基礎マインドセット - 深掘り読み物",
      difficulty: "advanced",
    },
    {
      id: 14,
      question: "営業における「傾聴」の正しい姿勢はどれか？",
      options: [
        "相手の話を聞きながら次の質問を考える",
        "相手の言葉を遮らず最後まで聴き切る",
        "重要なポイントだけを選んでメモを取る",
        "話が長い場合は要点をまとめて確認する",
      ],
      correctAnswer: 1,
      explanation: "傾聴とは相手の話を遮らず、最後まで聴き切ることです。これにより信頼関係が構築されます。",
      source: "A: 基礎マインドセット - 研修5",
      difficulty: "basic",
    },
    {
      id: 15,
      question: "顧客との長期的な関係構築で最も重要なことは？",
      options: [
        "定期的な訪問で接触頻度を高めること",
        "購入後も継続的な価値提供を行うこと",
        "競合情報を常に収集して報告すること",
        "新製品が出るたびに提案を行うこと",
      ],
      correctAnswer: 1,
      explanation: "売って終わりではなく、継続的な価値提供が長期的な信頼関係と追加受注につながります。",
      source: "A: 基礎マインドセット - 研修6",
      difficulty: "intermediate",
    },
    {
      id: 16,
      question: "「認知的不協和」を営業で活用するタイミングは？",
      options: [
        "初回訪問時に競合との違いを説明する時",
        "購入直後に選択の正しさを確認する時",
        "商談中に価格交渉を行う時に活用する",
        "提案書を作成する際の構成を考える時",
      ],
      correctAnswer: 1,
      explanation: "購入後は「本当に正しい選択だったか」と不安になります。その時に選択を肯定する情報を提供します。",
      source: "A: 基礎マインドセット - 深掘り読み物",
      difficulty: "advanced",
    },
    {
      id: 17,
      question: "営業マインドセットの土台となる考え方で正しいのは？",
      options: [
        "数字を追いかければ結果は自然とついてくる",
        "顧客の成功を自分の成功と捉えて行動する",
        "効率を重視して短時間で多く回ることが重要",
        "トーク力を磨けば誰でもトップ営業になれる",
      ],
      correctAnswer: 1,
      explanation: "顧客の成功を自分の成功と捉える姿勢が、持続的な営業成果と信頼関係構築の土台になります。",
      source: "A: 基礎マインドセット - 研修7",
      difficulty: "basic",
    },

    // ========================================
    // カテゴリB: 商品知識・Symphonyシリーズ（17問）
    // ========================================
    {
      id: 18,
      question: "Symphonyシリーズが提供する3つの価値はどれか？",
      options: [
        "安い・早い・簡単の3つの価値を提供する",
        "分かりやすい・つながる・売上が伸びる",
        "自動化・効率化・最適化の3つの価値",
        "集客・販売・管理の3つの価値を提供する",
      ],
      correctAnswer: 1,
      explanation: "Symphonyは「分かりやすい」「つながる」「売上が伸びる」の3つの価値で中古車販売を支援します。",
      source: "B: Symphonyシリーズ - 研修11",
      difficulty: "basic",
    },
    {
      id: 19,
      question: "Symphony販売管理の最大の特徴は何か？",
      options: [
        "業界最安値の月額料金で利用できること",
        "一度の入力で複数メディアに一括掲載",
        "AIによる自動価格設定機能があること",
        "24時間365日の電話サポートがあること",
      ],
      correctAnswer: 1,
      explanation: "Symphony販売管理は一度の入力で10以上の広告メディアに一括掲載でき、二重入力を解消します。",
      source: "B: Symphonyシリーズ - 研修12",
      difficulty: "basic",
    },
    {
      id: 20,
      question: "Symphony整備請求と販売管理を連携するメリットは？",
      options: [
        "請求書の印刷コストを削減できること",
        "顧客情報を共有しLTVを最大化できる",
        "整備士の作業効率が向上すること",
        "部品の在庫管理が自動化されること",
      ],
      correctAnswer: 1,
      explanation: "販売と整備のデータ連携により、顧客との長期関係を構築しLTV（顧客生涯価値）を最大化できます。",
      source: "B: Symphonyシリーズ - 研修13",
      difficulty: "intermediate",
    },
    {
      id: 21,
      question: "シンフォニーワンプラの主な手数料体系はどれか？",
      options: [
        "月額固定費と成約手数料の二段階制",
        "出品成約料と落札料の成約時のみ発生",
        "年間契約で一括払いすると割引適用",
        "在庫台数に応じた従量課金制を採用",
      ],
      correctAnswer: 1,
      explanation: "シンフォニーワンプラは固定費なしで、出品成約料と落札料の成約時のみ手数料が発生します。",
      source: "B: Symphonyシリーズ - 研修14",
      difficulty: "basic",
    },
    {
      id: 22,
      question: "ワンプラが競合サービスより優れている点は？",
      options: [
        "掲載台数が業界で最も多いこと",
        "業界最安水準の手数料とSymphony連携",
        "審査なしで誰でも利用開始できること",
        "全国どこでも即日配送に対応すること",
      ],
      correctAnswer: 1,
      explanation: "ワンプラは業界最安水準の手数料と、Symphony販売管理との自動連携が競合との差別化ポイントです。",
      source: "B: Symphonyシリーズ - 研修15",
      difficulty: "intermediate",
    },
    {
      id: 23,
      question: "製品間連携によるクロスセル提案のタイミングは？",
      options: [
        "初回商談時に全製品をセットで提案する",
        "顧客の成長や課題発生時に段階的に提案",
        "契約更新時にまとめて追加製品を提案",
        "競合からの乗り換え時に全製品を提案",
      ],
      correctAnswer: 1,
      explanation: "顧客の成長段階や新たな課題が発生したタイミングで、段階的にクロスセル提案を行います。",
      source: "B: Symphonyシリーズ - 研修16",
      difficulty: "intermediate",
    },
    {
      id: 24,
      question: "小規模店舗（10台以下）への提案で響くポイントは？",
      options: [
        "大企業も使っている信頼性の高さを訴求",
        "事務作業削減で接客時間を増やせること",
        "多店舗展開時のスケーラビリティを説明",
        "高度なデータ分析機能の活用方法を説明",
      ],
      correctAnswer: 1,
      explanation: "小規模店舗は「時間がない」が最大の課題。事務作業削減による接客時間増加が響きます。",
      source: "B: Symphonyシリーズ - 研修17",
      difficulty: "basic",
    },
    {
      id: 25,
      question: "中規模店舗（30-50台）が抱える典型的な課題は？",
      options: [
        "初期投資コストが大きすぎること",
        "スタッフ間の情報共有と在庫回転率",
        "広告メディアの選定に迷うこと",
        "オーナーの営業力に依存していること",
      ],
      correctAnswer: 1,
      explanation: "中規模店舗は組織化が進む中で、スタッフ間の情報共有や在庫回転率向上が課題になります。",
      source: "B: Symphonyシリーズ - 研修18",
      difficulty: "intermediate",
    },
    {
      id: 26,
      question: "大規模・多店舗への導入アプローチで正しいのは？",
      options: [
        "全店舗に一斉導入して早期に効果を出す",
        "1店舗でパイロット導入後に順次展開",
        "本部のみに導入して各店舗は後から対応",
        "繁忙期を避けて閑散期に一気に導入する",
      ],
      correctAnswer: 1,
      explanation: "大規模導入は1店舗でパイロット導入し、成功事例を作ってから順次展開するのが確実です。",
      source: "B: Symphonyシリーズ - 研修19",
      difficulty: "intermediate",
    },
    {
      id: 27,
      question: "Symphony導入のROI計算で考慮すべき効果は？",
      options: [
        "直接的なコスト削減のみを計算する",
        "時間削減・売上増加・コスト削減の3軸",
        "競合との価格差のみを比較して計算",
        "導入後1ヶ月の効果のみで判断する",
      ],
      correctAnswer: 1,
      explanation: "ROIは時間削減効果、売上増加効果、コスト削減効果の3軸で総合的に計算します。",
      source: "B: Symphonyシリーズ - 研修20",
      difficulty: "basic",
    },
    {
      id: 28,
      question: "顧客から「高くないですか？」と言われた時の対応は？",
      options: [
        "すぐに値引きを提示して契約を急ぐ",
        "ROI試算を見せて投資対効果を説明",
        "他社はもっと高いと競合比較を行う",
        "機能を減らした安いプランを提案する",
      ],
      correctAnswer: 1,
      explanation: "価格の妥当性はROI試算で説明します。投資対効果を数字で示すことで納得を得られます。",
      source: "B: Symphonyシリーズ - 研修21",
      difficulty: "basic",
    },
    {
      id: 29,
      question: "効果的なデモンストレーションの構成として正しいのは？",
      options: [
        "全機能を網羅的に30分かけて説明する",
        "顧客の課題に絞りビフォーアフターを見せる",
        "操作スピードを上げて多くの機能を紹介",
        "カタログを見せながら口頭で説明する",
      ],
      correctAnswer: 1,
      explanation: "デモの目的は「価値を体験してもらうこと」。顧客の課題解決にフォーカスしたデモが効果的です。",
      source: "B: Symphonyシリーズ - 研修22",
      difficulty: "intermediate",
    },
    {
      id: 30,
      question: "Symphony導入で実現できる入力作業の削減率は？",
      options: [
        "約20%の入力作業を削減できる",
        "約50%の入力作業を削減できる",
        "約80%の入力作業を削減できる",
        "入力作業を完全に自動化できる",
      ],
      correctAnswer: 1,
      explanation: "一元管理による二重入力解消で、入力作業を約50%削減できます（実績ベース）。",
      source: "B: Symphonyシリーズ - 研修12",
      difficulty: "intermediate",
    },
    {
      id: 31,
      question: "整備ビジネスが中古車販売店にとって重要な理由は？",
      options: [
        "車両販売より利益率が高いから",
        "車検は定期的に発生する安定収益源だから",
        "整備士の雇用を維持するために必要だから",
        "法律で整備部門の設置が義務付けられている",
      ],
      correctAnswer: 1,
      explanation: "車検は2年に1回必ず発生する継続収益です。価格競争の激しい車販を補完する安定収益源になります。",
      source: "B: Symphonyシリーズ - 研修13",
      difficulty: "intermediate",
    },
    {
      id: 32,
      question: "ワンプラで「仕入れ」と「業販出品」両方ができる利点は？",
      options: [
        "手数料が両方とも無料になること",
        "仕入れルート拡大と在庫処分が同時に可能",
        "オークション会員でなくても利用できる",
        "全国どこでも送料無料で取引できる",
      ],
      correctAnswer: 1,
      explanation: "ワンプラは仕入れルートの拡大と売れない在庫の業販出品の両方ができ、在庫リスクを軽減します。",
      source: "B: Symphonyシリーズ - 研修14",
      difficulty: "basic",
    },
    {
      id: 33,
      question: "Symphonyの「100万件超のデータ」の活用方法は？",
      options: [
        "過去の販売履歴を検索できる",
        "適正価格の判断に活用できる",
        "顧客の個人情報を管理できる",
        "競合店舗の情報を分析できる",
      ],
      correctAnswer: 1,
      explanation: "100万件超のリアルタイム車両データにより、相場に基づいた適正価格の判断ができます。",
      source: "B: Symphonyシリーズ - 研修11",
      difficulty: "intermediate",
    },
    {
      id: 34,
      question: "Symphony導入提案で「使いこなせるか不安」への回答は？",
      options: [
        "マニュアルを熟読すれば大丈夫です",
        "直感的UIと研修・専任サポートがあります",
        "使えない機能は使わなくても大丈夫です",
        "最初は私が代わりに操作します",
      ],
      correctAnswer: 1,
      explanation: "ITが苦手な方でも安心できるよう、直感的なUI、導入時研修、専任サポートがあることを伝えます。",
      source: "B: Symphonyシリーズ - 研修21",
      difficulty: "basic",
    },

    // ========================================
    // カテゴリC: 営業プロセス（17問）
    // ========================================
    {
      id: 35,
      question: "営業プロセスの最初のステップとして正しいのは？",
      options: [
        "商品知識を完璧に習得すること",
        "見込み客の発掘とリスト作成",
        "提案資料のテンプレートを作成",
        "競合他社の情報を収集すること",
      ],
      correctAnswer: 1,
      explanation: "営業プロセスはまず見込み客の発掘から始まります。ターゲット選定がその後の効率を決めます。",
      source: "C: 営業プロセス - 研修23",
      difficulty: "basic",
    },
    {
      id: 36,
      question: "テレアポで最初の15秒で伝えるべきことは？",
      options: [
        "自社製品の特徴と価格情報",
        "自己紹介と電話した理由・目的",
        "競合との比較における優位性",
        "成功事例と導入効果の数字",
      ],
      correctAnswer: 1,
      explanation: "最初の15秒で「誰が」「なぜ電話したか」を明確にし、相手の関心を引くことが重要です。",
      source: "C: 営業プロセス - 研修24",
      difficulty: "basic",
    },
    {
      id: 37,
      question: "初回訪問の目的として最も重要なのは何か？",
      options: [
        "製品のデモンストレーションを行う",
        "顧客の課題とニーズを深く理解する",
        "見積書を提示して価格交渉を行う",
        "契約書の内容を詳しく説明する",
      ],
      correctAnswer: 1,
      explanation: "初回訪問の主目的は課題とニーズの理解です。提案は十分な理解の後に行います。",
      source: "C: 営業プロセス - 研修25",
      difficulty: "basic",
    },
    {
      id: 38,
      question: "提案書作成で最も重視すべき点は何か？",
      options: [
        "デザインの美しさとページ数の多さ",
        "顧客の課題と解決策の明確な対応関係",
        "自社製品の全機能を網羅的に記載",
        "競合他社との詳細な比較表の掲載",
      ],
      correctAnswer: 1,
      explanation: "提案書は顧客の課題に対する解決策を明確に示すものです。課題と解決策の対応が最重要です。",
      source: "C: 営業プロセス - 研修26",
      difficulty: "intermediate",
    },
    {
      id: 39,
      question: "クロージングの最適なタイミングを見極める方法は？",
      options: [
        "商談開始から30分経過した時点",
        "顧客の購買シグナルを見逃さない",
        "全ての質問に回答し終えた時点",
        "見積書を提出してから3日後",
      ],
      correctAnswer: 1,
      explanation: "クロージングは顧客の購買シグナル（質問の変化、前のめりの姿勢など）を察知して行います。",
      source: "C: 営業プロセス - 研修27",
      difficulty: "intermediate",
    },
    {
      id: 40,
      question: "営業パイプライン管理で重要な指標はどれか？",
      options: [
        "訪問回数と移動距離の効率",
        "各ステージの案件数と進捗率",
        "提案書の作成にかかった時間",
        "顧客との通話時間の長さ",
      ],
      correctAnswer: 1,
      explanation: "パイプライン管理では各ステージの案件数と進捗率を可視化し、ボトルネックを特定します。",
      source: "C: 営業プロセス - 研修28",
      difficulty: "intermediate",
    },
    {
      id: 41,
      question: "商談で「予算がない」と言われた時の対応は？",
      options: [
        "予算ができたら連絡くださいと引く",
        "本当の懸念点を確認する質問をする",
        "すぐに大幅な値引きを提示する",
        "分割払いプランを即座に提案する",
      ],
      correctAnswer: 1,
      explanation: "「予算がない」は本当の理由ではないことが多いです。質問で真の懸念点を確認します。",
      source: "C: 営業プロセス - 深掘り読み物",
      difficulty: "advanced",
    },
    {
      id: 42,
      question: "BANTフレームワークの4要素として正しいのは？",
      options: [
        "Business, Analysis, Need, Time",
        "Budget, Authority, Need, Timeline",
        "Benefit, Action, Negotiation, Trust",
        "Base, Approach, Network, Target",
      ],
      correctAnswer: 1,
      explanation: "BANTは予算(Budget)、決裁権(Authority)、ニーズ(Need)、導入時期(Timeline)の4要素です。",
      source: "C: 営業プロセス - 深掘り読み物",
      difficulty: "advanced",
    },
    {
      id: 43,
      question: "MEDDICフレームワークで「Economic Buyer」とは？",
      options: [
        "製品を実際に使用するエンドユーザー",
        "最終的な購買決定権を持つ人物",
        "予算管理を担当する経理担当者",
        "技術的な評価を行う担当者",
      ],
      correctAnswer: 1,
      explanation: "Economic Buyerは最終的な購買決定権を持つ人物です。この人物へのアプローチが成約の鍵です。",
      source: "C: 営業プロセス - 深掘り読み物",
      difficulty: "advanced",
    },
    {
      id: 44,
      question: "商談の「チャンピオン」を作る意義として正しいのは？",
      options: [
        "競合情報を内部から入手できるから",
        "社内で自社の代わりに推進してくれるから",
        "意思決定を早めてもらえるから",
        "値引き交渉を有利に進められるから",
      ],
      correctAnswer: 1,
      explanation: "チャンピオンは顧客社内で自社製品を推進してくれる味方です。不在時の社内調整も担います。",
      source: "C: 営業プロセス - 深掘り読み物",
      difficulty: "advanced",
    },
    {
      id: 45,
      question: "「ペインポイント」の特定で効果的な質問は？",
      options: [
        "御社の売上はいくらですか？",
        "現状で最も困っていることは何ですか？",
        "競合他社はどこを使っていますか？",
        "いつまでに導入したいですか？",
      ],
      correctAnswer: 1,
      explanation: "ペインポイントは顧客の「痛み」です。直接的に困っていることを聞くことで特定できます。",
      source: "C: 営業プロセス - 研修25",
      difficulty: "basic",
    },
    {
      id: 46,
      question: "商談で複数の意思決定者がいる場合の対応は？",
      options: [
        "一人のキーマンに絞ってアプローチ",
        "全員のニーズと懸念を個別に把握する",
        "最も役職が高い人だけに説明する",
        "会議形式でまとめて説明する",
      ],
      correctAnswer: 1,
      explanation: "複数の意思決定者がいる場合、それぞれの立場でのニーズと懸念を個別に把握することが重要です。",
      source: "C: 営業プロセス - 深掘り読み物",
      difficulty: "advanced",
    },
    {
      id: 47,
      question: "テストクロージングの正しい使い方は？",
      options: [
        "契約書を見せて反応を確認する方法",
        "仮定の質問で購買意欲を確認する方法",
        "期間限定特典で決断を迫る方法",
        "上司の承認が必要と伝える方法",
      ],
      correctAnswer: 1,
      explanation: "テストクロージングは「もし〜だとしたら」と仮定の質問で顧客の購買意欲を確認する技法です。",
      source: "C: 営業プロセス - 研修27",
      difficulty: "intermediate",
    },
    {
      id: 48,
      question: "失注案件の分析で最も重要なことは？",
      options: [
        "競合との価格差を詳細に分析する",
        "失注理由を正確に把握し次に活かす",
        "担当者を変えて再アプローチする",
        "失注した顧客リストを作成する",
      ],
      correctAnswer: 1,
      explanation: "失注理由を正確に把握し、次の商談に活かすことが継続的な改善につながります。",
      source: "C: 営業プロセス - 研修28",
      difficulty: "intermediate",
    },
    {
      id: 49,
      question: "リードナーチャリングの目的として正しいのは？",
      options: [
        "すぐに商談化できる見込み客を選別",
        "時間をかけて購買意欲を高める活動",
        "不要なリードをリストから削除する",
        "リードの個人情報を詳しく収集する",
      ],
      correctAnswer: 1,
      explanation: "リードナーチャリングは、まだ購買準備ができていない見込み客を育成し、購買意欲を高める活動です。",
      source: "C: 営業プロセス - 深掘り読み物",
      difficulty: "advanced",
    },
    {
      id: 50,
      question: "商談のゴール設定で正しいのはどれか？",
      options: [
        "とにかく契約を取ることをゴールにする",
        "次のステップに進む合意を得ること",
        "自社製品の全てを説明し終えること",
        "顧客の全ての質問に回答すること",
      ],
      correctAnswer: 1,
      explanation: "各商談のゴールは「次のステップに進む合意」です。一気に契約を目指すのではなく段階的に進めます。",
      source: "C: 営業プロセス - 研修26",
      difficulty: "basic",
    },
    {
      id: 51,
      question: "アポイント取得率を上げるための工夫は？",
      options: [
        "電話の回数を増やして確率で勝負",
        "顧客にとってのメリットを明確に伝える",
        "できるだけ早い日程を提案する",
        "上司の名前を出して権威を示す",
      ],
      correctAnswer: 1,
      explanation: "アポ取得率向上には、顧客にとってのメリット（会う価値）を明確に伝えることが効果的です。",
      source: "C: 営業プロセス - 研修24",
      difficulty: "intermediate",
    },

    // ========================================
    // カテゴリD: 商談テクニック（17問）
    // ========================================
    {
      id: 52,
      question: "商談の冒頭で最初に行うべきことは？",
      options: [
        "自社製品のカタログを配布すること",
        "アイスブレイクで場を和ませること",
        "本日の議題と目的を確認すること",
        "名刺交換を丁寧に行うこと",
      ],
      correctAnswer: 1,
      explanation: "商談冒頭ではアイスブレイクで場を和ませ、信頼関係構築の土台を作ります。",
      source: "D: 商談テクニック - 研修32",
      difficulty: "basic",
    },
    {
      id: 53,
      question: "オープンクエスチョンの特徴として正しいのは？",
      options: [
        "「はい」「いいえ」で答えられる質問",
        "自由に回答でき情報を深掘りできる質問",
        "選択肢を提示して選んでもらう質問",
        "数値で回答してもらう定量的な質問",
      ],
      correctAnswer: 1,
      explanation: "オープンクエスチョンは「なぜ」「どのように」など自由回答を促し、深い情報を引き出せます。",
      source: "D: 商談テクニック - 研修33",
      difficulty: "basic",
    },
    {
      id: 54,
      question: "顧客の反論に対する最初の対応として適切なのは？",
      options: [
        "すぐに論理的な反論で説得を試みる",
        "まず反論の背景にある懸念を理解する",
        "他社事例を見せて安心させる",
        "上司に相談すると伝えて持ち帰る",
      ],
      correctAnswer: 1,
      explanation: "反論には必ず背景があります。まず懸念を理解してから、適切な対応を考えます。",
      source: "D: 商談テクニック - 研修34",
      difficulty: "intermediate",
    },
    {
      id: 55,
      question: "価格交渉で値引きを求められた時の対応は？",
      options: [
        "即座に可能な範囲で値引きを提示",
        "値引きの前に価値を再確認する",
        "「これ以上は無理です」と断る",
        "上司に確認しますと一旦持ち帰る",
      ],
      correctAnswer: 1,
      explanation: "値引き要求には、まず提供価値を再確認します。価値が認められれば価格への不満は減少します。",
      source: "D: 商談テクニック - 研修35",
      difficulty: "intermediate",
    },
    {
      id: 56,
      question: "プレゼンテーションで最も重要なことは？",
      options: [
        "スライドのデザインを美しくすること",
        "聴衆のニーズに合わせた内容にすること",
        "全ての機能を漏れなく説明すること",
        "時間通りに終わらせること",
      ],
      correctAnswer: 1,
      explanation: "プレゼンは聴衆のニーズに合わせることが最重要。相手が聞きたいことを中心に構成します。",
      source: "D: 商談テクニック - 研修36",
      difficulty: "basic",
    },
    {
      id: 57,
      question: "商談中に顧客が腕を組んだ時の対応は？",
      options: [
        "話を続けてより詳しく説明する",
        "オープンな質問で対話に戻す",
        "資料を渡して読んでもらう",
        "一旦休憩を提案する",
      ],
      correctAnswer: 1,
      explanation: "腕組みは防御的な姿勢の表れです。オープンな質問で相手に発言機会を与え、対話に戻します。",
      source: "D: 商談テクニック - 深掘り読み物",
      difficulty: "advanced",
    },
    {
      id: 58,
      question: "「ミラーリング」を商談で使う効果は？",
      options: [
        "自分の主張を相手に映し出す効果",
        "相手との親近感と信頼を高める効果",
        "相手の弱点を見つけ出す効果",
        "商談時間を短縮する効果",
      ],
      correctAnswer: 1,
      explanation: "ミラーリングは相手の姿勢や話し方を鏡のように合わせることで、親近感と信頼を高めます。",
      source: "D: 商談テクニック - 深掘り読み物",
      difficulty: "advanced",
    },
    {
      id: 59,
      question: "クロージングで「沈黙」が効果的な理由は？",
      options: [
        "相手が考える時間を与えられるから",
        "威圧感を与えて決断を促すから",
        "自分の緊張を隠せるから",
        "次の質問を考える時間ができるから",
      ],
      correctAnswer: 0,
      explanation: "クロージング後の沈黙は、相手に考える時間を与えます。焦って話し続けないことが重要です。",
      source: "D: 商談テクニック - 研修37",
      difficulty: "intermediate",
    },
    {
      id: 60,
      question: "「二者択一法」のクロージングとはどのような方法か？",
      options: [
        "契約するかしないかを直接確認する方法",
        "AとBどちらがいいかを選んでもらう方法",
        "二人の上司に同時に提案する方法",
        "二回に分けて契約を進める方法",
      ],
      correctAnswer: 1,
      explanation: "二者択一法は「AプランとBプラン、どちらがご希望ですか？」と選択肢を示す技法です。",
      source: "D: 商談テクニック - 研修37",
      difficulty: "basic",
    },
    {
      id: 61,
      question: "顧客が「競合と比較検討中」と言った時の対応は？",
      options: [
        "競合の悪い点を指摘して牽制する",
        "比較検討のポイントを確認して差別化",
        "値引きを提示して早期決定を促す",
        "検討結果を待つと伝えて引き下がる",
      ],
      correctAnswer: 1,
      explanation: "比較検討のポイントを確認し、そのポイントでの自社の強みを明確に伝えることが重要です。",
      source: "D: 商談テクニック - 研修34",
      difficulty: "intermediate",
    },
    {
      id: 62,
      question: "商談で「ストーリーテリング」が効果的な理由は？",
      options: [
        "話が長くなり商談時間を稼げるから",
        "論理より感情に訴え記憶に残りやすい",
        "自分の話術をアピールできるから",
        "顧客の質問を減らせるから",
      ],
      correctAnswer: 1,
      explanation: "ストーリーは論理的説明より感情に訴え、記憶に残りやすいため、説得力が増します。",
      source: "D: 商談テクニック - 深掘り読み物",
      difficulty: "advanced",
    },
    {
      id: 63,
      question: "「FABE法」のプレゼン構成で正しい順序は？",
      options: [
        "Feature → Advantage → Benefit → Evidence",
        "Fact → Analysis → Benefit → Example",
        "Focus → Action → Benefit → End",
        "Feature → Action → Base → Evidence",
      ],
      correctAnswer: 0,
      explanation: "FABEは特徴→利点→便益→証拠の順で説明し、顧客にとっての価値を明確にする技法です。",
      source: "D: 商談テクニック - 深掘り読み物",
      difficulty: "advanced",
    },
    {
      id: 64,
      question: "商談での「ペーシング」の正しい使い方は？",
      options: [
        "早口で話して多くの情報を伝える方法",
        "相手の話すスピードに合わせる方法",
        "一定のペースで話し続ける方法",
        "間を取らずにテンポよく話す方法",
      ],
      correctAnswer: 1,
      explanation: "ペーシングは相手の話すスピードやテンポに合わせることで、親近感と信頼を構築します。",
      source: "D: 商談テクニック - 深掘り読み物",
      difficulty: "advanced",
    },
    {
      id: 65,
      question: "顧客の「今は忙しい」への効果的な対応は？",
      options: [
        "わかりました、と引き下がり後日連絡",
        "忙しい理由を確認し短時間の価値を提案",
        "上司からお電話させますと伝える",
        "メールで資料を送りますと提案",
      ],
      correctAnswer: 1,
      explanation: "「忙しい」の裏にある理由を確認し、短時間でも価値があることを伝えて時間を確保します。",
      source: "D: 商談テクニック - 研修34",
      difficulty: "intermediate",
    },
    {
      id: 66,
      question: "商談のクロージングで避けるべきことは？",
      options: [
        "顧客に考える時間を与えること",
        "顧客の決断を急かすこと",
        "導入後のイメージを伝えること",
        "不明点がないか確認すること",
      ],
      correctAnswer: 1,
      explanation: "決断を急かすと顧客は防御的になります。余裕を持たせた方が成約率は上がります。",
      source: "D: 商談テクニック - 研修37",
      difficulty: "basic",
    },
    {
      id: 67,
      question: "「推定承諾法」のクロージングの特徴は？",
      options: [
        "購入を前提とした質問で話を進める方法",
        "購入を強く推薦する方法",
        "購入しないとどうなるかを伝える方法",
        "上司が承諾したと伝える方法",
      ],
      correctAnswer: 0,
      explanation: "推定承諾法は「導入後の運用体制はどうされますか？」など購入前提の質問で自然に進めます。",
      source: "D: 商談テクニック - 深掘り読み物",
      difficulty: "advanced",
    },
    {
      id: 68,
      question: "商談中のメモの取り方で正しいのは？",
      options: [
        "全ての発言を漏らさず記録する",
        "キーワードと重要ポイントを記録する",
        "メモは取らず会話に集中する",
        "録音して後から文字起こしする",
      ],
      correctAnswer: 1,
      explanation: "全て記録すると会話に集中できません。キーワードと重要ポイントに絞ってメモを取ります。",
      source: "D: 商談テクニック - 研修33",
      difficulty: "basic",
    },

    // ========================================
    // カテゴリE: 顧客管理・フォロー（16問）
    // ========================================
    {
      id: 69,
      question: "CRM（顧客管理システム）を導入する最大の目的は？",
      options: [
        "営業の行動を監視すること",
        "顧客との関係を一元管理し深めること",
        "報告書作成の手間を削減すること",
        "営業成績をランキング化すること",
      ],
      correctAnswer: 1,
      explanation: "CRMの目的は顧客情報を一元管理し、組織として顧客との関係を深めることです。",
      source: "E: 顧客管理 - 研修41",
      difficulty: "basic",
    },
    {
      id: 70,
      question: "顧客のLTV（顧客生涯価値）を高める方法は？",
      options: [
        "初回購入時に高額商品を販売する",
        "継続的な価値提供で長期関係を構築",
        "紹介キャンペーンで新規顧客を増やす",
        "値引きを行い購入頻度を上げる",
      ],
      correctAnswer: 1,
      explanation: "LTVは継続的な価値提供と長期関係構築によって高まります。売って終わりでは上がりません。",
      source: "E: 顧客管理 - 研修42",
      difficulty: "intermediate",
    },
    {
      id: 71,
      question: "既存顧客へのフォローで最も重要なタイミングは？",
      options: [
        "契約更新の1ヶ月前のタイミング",
        "導入直後の不安が大きい時期",
        "競合からのアプローチがあった時",
        "自社の新製品がリリースされた時",
      ],
      correctAnswer: 1,
      explanation: "導入直後は不安が大きく、丁寧なフォローが信頼構築と継続利用につながります。",
      source: "E: 顧客管理 - 研修43",
      difficulty: "intermediate",
    },
    {
      id: 72,
      question: "顧客からのクレーム対応で最初に行うべきことは？",
      options: [
        "事実確認をして原因を特定する",
        "まず謝罪し顧客の話を傾聴する",
        "解決策を即座に提示する",
        "上司に報告して指示を仰ぐ",
      ],
      correctAnswer: 1,
      explanation: "クレーム対応はまず謝罪と傾聴から。感情を受け止めてから原因特定と解決に進みます。",
      source: "E: 顧客管理 - 研修44",
      difficulty: "basic",
    },
    {
      id: 73,
      question: "顧客の「解約したい」への効果的な対応は？",
      options: [
        "解約手続きを迅速に進める対応",
        "解約理由を確認し改善提案を行う対応",
        "違約金について説明する対応",
        "上司に代わってもらう対応",
      ],
      correctAnswer: 1,
      explanation: "解約希望には理由を確認し、改善提案で引き留めを試みます。理由によっては解約阻止できます。",
      source: "E: 顧客管理 - 研修44",
      difficulty: "intermediate",
    },
    {
      id: 74,
      question: "顧客セグメンテーションの目的として正しいのは？",
      options: [
        "優良顧客だけに営業リソースを集中",
        "顧客特性に応じた最適なアプローチ",
        "取引額の小さい顧客を切り捨てる",
        "顧客リストを整理して管理を簡素化",
      ],
      correctAnswer: 1,
      explanation: "セグメンテーションは顧客を特性ごとに分け、それぞれに最適なアプローチを行うためです。",
      source: "E: 顧客管理 - 深掘り読み物",
      difficulty: "advanced",
    },
    {
      id: 75,
      question: "NPS（ネットプロモータースコア）の計算方法は？",
      options: [
        "満足度の平均点を100点満点で算出",
        "推奨者の割合から批判者の割合を引く",
        "リピート率と紹介率を掛け合わせる",
        "クレーム数を顧客数で割って算出",
      ],
      correctAnswer: 1,
      explanation: "NPSは「他者に推奨したいか」を11段階で聞き、推奨者(9-10)％から批判者(0-6)％を引きます。",
      source: "E: 顧客管理 - 深掘り読み物",
      difficulty: "advanced",
    },
    {
      id: 76,
      question: "顧客の「担当者が変わった」への対応で正しいのは？",
      options: [
        "新担当者に自社製品を一から説明",
        "まず新担当者のニーズと状況を確認",
        "前担当者との関係を新担当者に伝える",
        "上司同士の挨拶の場を設定する",
      ],
      correctAnswer: 1,
      explanation: "担当者変更時は、まず新担当者のニーズと状況を確認し、関係構築をやり直します。",
      source: "E: 顧客管理 - 研修45",
      difficulty: "intermediate",
    },
    {
      id: 77,
      question: "アップセルとクロスセルの違いで正しいのは？",
      options: [
        "アップセルは新規、クロスセルは既存向け",
        "アップセルは上位版、クロスセルは関連商品",
        "アップセルは法人、クロスセルは個人向け",
        "アップセルは長期、クロスセルは短期契約",
      ],
      correctAnswer: 1,
      explanation: "アップセルは上位グレードへの誘導、クロスセルは関連する別商品の提案です。",
      source: "E: 顧客管理 - 研修46",
      difficulty: "basic",
    },
    {
      id: 78,
      question: "顧客満足度調査の結果を活かす正しい方法は？",
      options: [
        "満足度が高い顧客にだけ追加提案",
        "不満の声を分析し改善アクションにつなげる",
        "調査結果を社内報告して共有する",
        "次回調査時の比較データとして保管",
      ],
      correctAnswer: 1,
      explanation: "満足度調査は不満の声を分析し、具体的な改善アクションにつなげることで価値を発揮します。",
      source: "E: 顧客管理 - 深掘り読み物",
      difficulty: "advanced",
    },
    {
      id: 79,
      question: "「休眠顧客」の掘り起こしで効果的な方法は？",
      options: [
        "営業電話を頻繁にかけてアプローチ",
        "過去の取引履歴を分析し価値ある情報提供",
        "大幅な値引きキャンペーンを実施",
        "新人営業の練習相手として活用",
      ],
      correctAnswer: 1,
      explanation: "休眠顧客には過去の取引を分析し、相手にとって価値ある情報を提供することが効果的です。",
      source: "E: 顧客管理 - 研修47",
      difficulty: "intermediate",
    },
    {
      id: 80,
      question: "顧客紹介を依頼する最適なタイミングは？",
      options: [
        "契約直後のテンションが高い時",
        "顧客が成果を実感した時",
        "契約更新の交渉時にお願いする",
        "定例ミーティングの最後に依頼",
      ],
      correctAnswer: 1,
      explanation: "紹介依頼は顧客が成果を実感し、満足度が高まったタイミングが最も効果的です。",
      source: "E: 顧客管理 - 研修48",
      difficulty: "intermediate",
    },
    {
      id: 81,
      question: "顧客データベースで最低限管理すべき情報は？",
      options: [
        "氏名と連絡先のみで十分である",
        "取引履歴・接触履歴・ニーズ情報など",
        "競合他社の利用状況のみ",
        "決裁権の有無だけ管理すれば良い",
      ],
      correctAnswer: 1,
      explanation: "顧客DBには取引履歴、接触履歴、ニーズ、課題など、関係構築に必要な情報を管理します。",
      source: "E: 顧客管理 - 研修41",
      difficulty: "basic",
    },
    {
      id: 82,
      question: "RFM分析の3つの指標として正しいのは？",
      options: [
        "Revenue, Frequency, Market",
        "Recency, Frequency, Monetary",
        "Rate, Factor, Measure",
        "Reach, Focus, Method",
      ],
      correctAnswer: 1,
      explanation: "RFMは最終購買日(Recency)、購買頻度(Frequency)、購買金額(Monetary)の3指標で顧客を分析します。",
      source: "E: 顧客管理 - 深掘り読み物",
      difficulty: "advanced",
    },
    {
      id: 83,
      question: "カスタマーサクセスの考え方で正しいのは？",
      options: [
        "顧客からの問い合わせに対応すること",
        "顧客の成功を能動的に支援すること",
        "顧客満足度を定期的に測定すること",
        "顧客の要望を全て受け入れること",
      ],
      correctAnswer: 1,
      explanation: "カスタマーサクセスは受動的な対応ではなく、能動的に顧客の成功を支援する考え方です。",
      source: "E: 顧客管理 - 深掘り読み物",
      difficulty: "advanced",
    },
    {
      id: 84,
      question: "顧客との定期ミーティングで重要なことは？",
      options: [
        "自社の新製品情報を必ず紹介する",
        "顧客の状況変化や新たなニーズを確認",
        "前回の議事録を一緒に読み合わせる",
        "毎回同じアジェンダで効率化する",
      ],
      correctAnswer: 1,
      explanation: "定期ミーティングでは顧客の状況変化や新たなニーズを確認し、提案機会を見つけます。",
      source: "E: 顧客管理 - 研修43",
      difficulty: "basic",
    },

    // ========================================
    // カテゴリF: セルフマネジメント（16問）
    // ========================================
    {
      id: 85,
      question: "営業の時間管理で最も重要なことは？",
      options: [
        "できるだけ多くの顧客を訪問すること",
        "重要度と緊急度で優先順位をつけること",
        "上司の指示を最優先で対応すること",
        "残業を減らして効率化すること",
      ],
      correctAnswer: 1,
      explanation: "時間管理では重要度と緊急度のマトリクスで優先順位をつけ、重要なことに時間を使います。",
      source: "F: セルフマネジメント - 研修50",
      difficulty: "basic",
    },
    {
      id: 86,
      question: "営業目標設定で「SMARTの法則」の「S」は？",
      options: [
        "Simple（シンプルな目標）",
        "Specific（具体的な目標）",
        "Strong（強い意志の目標）",
        "Short（短期の目標）",
      ],
      correctAnswer: 1,
      explanation: "SMARTのSはSpecific（具体的）です。曖昧でない明確な目標を設定します。",
      source: "F: セルフマネジメント - 研修51",
      difficulty: "basic",
    },
    {
      id: 87,
      question: "営業でPDCAサイクルを回す意義は？",
      options: [
        "上司への報告を効率化できるから",
        "継続的な改善で成果を向上させるため",
        "業務を標準化できるから",
        "チーム内で情報共有できるから",
      ],
      correctAnswer: 1,
      explanation: "PDCAは計画→実行→評価→改善を繰り返し、継続的に成果を向上させるためのサイクルです。",
      source: "F: セルフマネジメント - 研修52",
      difficulty: "basic",
    },
    {
      id: 88,
      question: "営業におけるモチベーション維持の方法は？",
      options: [
        "常に高い目標を設定し追い込む",
        "小さな成功体験を積み重ねる",
        "成績上位者と自分を常に比較する",
        "報酬だけを目標にして頑張る",
      ],
      correctAnswer: 1,
      explanation: "モチベーション維持には小さな成功体験の積み重ねが効果的。達成感が次の行動につながります。",
      source: "F: セルフマネジメント - 研修53",
      difficulty: "intermediate",
    },
    {
      id: 89,
      question: "営業日報を書く本来の目的は？",
      options: [
        "上司が営業活動を管理するため",
        "自己の活動を振り返り改善するため",
        "会社の記録として残すため",
        "労働時間を証明するため",
      ],
      correctAnswer: 1,
      explanation: "営業日報の本来の目的は、自己の活動を振り返り、改善点を見つけることです。",
      source: "F: セルフマネジメント - 研修54",
      difficulty: "basic",
    },
    {
      id: 90,
      question: "スランプから抜け出すための効果的な方法は？",
      options: [
        "量をこなして確率で成果を出す",
        "基本に立ち返り成功パターンを見直す",
        "新しい手法を次々と試してみる",
        "しばらく休んでリフレッシュする",
      ],
      correctAnswer: 1,
      explanation: "スランプ時は基本に立ち返り、過去の成功パターンを見直すことが効果的です。",
      source: "F: セルフマネジメント - 研修55",
      difficulty: "intermediate",
    },
    {
      id: 91,
      question: "「パレートの法則（80:20の法則）」の営業での活用は？",
      options: [
        "上位20%の営業が80%の売上を上げる",
        "上位20%の顧客に集中してアプローチ",
        "時間の20%を勉強に使う",
        "営業の80%は既存顧客対応に使う",
      ],
      correctAnswer: 1,
      explanation: "売上の80%は上位20%の顧客からもたらされます。この顧客に集中することで効率が上がります。",
      source: "F: セルフマネジメント - 深掘り読み物",
      difficulty: "advanced",
    },
    {
      id: 92,
      question: "営業の「ゾーン」に入る条件として正しいのは？",
      options: [
        "適度なプレッシャーと高いスキルの組合せ",
        "完全にリラックスした状態であること",
        "極度の緊張状態を維持すること",
        "長時間の連続勤務による集中",
      ],
      correctAnswer: 0,
      explanation: "フロー状態（ゾーン）は、適度な挑戦とスキルが釣り合った時に生まれる最適な集中状態です。",
      source: "F: セルフマネジメント - 深掘り読み物",
      difficulty: "advanced",
    },
    {
      id: 93,
      question: "ストレスマネジメントで効果的な方法は？",
      options: [
        "ストレスを感じないように努力する",
        "ストレスの原因を特定し対処法を考える",
        "ストレスは気にしないことが一番",
        "常にポジティブに考えるように努める",
      ],
      correctAnswer: 1,
      explanation: "ストレスは避けられません。原因を特定し、適切な対処法を考えることが重要です。",
      source: "F: セルフマネジメント - 研修56",
      difficulty: "intermediate",
    },
    {
      id: 94,
      question: "営業スキル向上のための自己投資で効果的なのは？",
      options: [
        "営業本を年間100冊読むこと",
        "学んだことを実践し振り返ること",
        "高額なセミナーに参加すること",
        "トップ営業の動画を毎日見ること",
      ],
      correctAnswer: 1,
      explanation: "学びの定着には実践と振り返りが不可欠。インプットだけでなくアウトプットが重要です。",
      source: "F: セルフマネジメント - 研修57",
      difficulty: "intermediate",
    },
    {
      id: 95,
      question: "「成長マインドセット」の特徴として正しいのは？",
      options: [
        "自分の能力は生まれつき決まっている",
        "努力と学習で能力は伸ばせると信じる",
        "失敗を避けて確実な方法を選ぶ",
        "他人との競争で自分を高める",
      ],
      correctAnswer: 1,
      explanation: "成長マインドセットは、努力と学習で能力は伸ばせるという信念。失敗も成長機会と捉えます。",
      source: "F: セルフマネジメント - 深掘り読み物",
      difficulty: "advanced",
    },
    {
      id: 96,
      question: "「アイゼンハワーマトリクス」の第2領域とは？",
      options: [
        "緊急かつ重要なタスク",
        "緊急ではないが重要なタスク",
        "緊急だが重要ではないタスク",
        "緊急でも重要でもないタスク",
      ],
      correctAnswer: 1,
      explanation: "第2領域は「緊急ではないが重要」なタスク。ここに時間を使うことが成果につながります。",
      source: "F: セルフマネジメント - 深掘り読み物",
      difficulty: "advanced",
    },
    {
      id: 97,
      question: "営業のルーティン化で得られる効果は？",
      options: [
        "毎日同じ行動で飽きが来ない",
        "意思決定の負担を減らし集中できる",
        "上司への報告が簡単になる",
        "残業時間を削減できる",
      ],
      correctAnswer: 1,
      explanation: "ルーティン化により意思決定の負担が減り、重要なことに集中できるようになります。",
      source: "F: セルフマネジメント - 研修58",
      difficulty: "intermediate",
    },
    {
      id: 98,
      question: "「レジリエンス」を高める方法として正しいのは？",
      options: [
        "失敗しないように慎重に行動する",
        "失敗から学び回復する力を養う",
        "常に成功イメージだけを持つ",
        "ストレスを感じる環境を避ける",
      ],
      correctAnswer: 1,
      explanation: "レジリエンスは逆境から回復する力。失敗を恐れず、そこから学ぶ姿勢が重要です。",
      source: "F: セルフマネジメント - 深掘り読み物",
      difficulty: "advanced",
    },
    {
      id: 99,
      question: "長期的なキャリア形成で営業が意識すべきことは？",
      options: [
        "常に数字を追い求め続けること",
        "専門性と人脈を計画的に築くこと",
        "できるだけ早く管理職になること",
        "一つの会社に長く勤めること",
      ],
      correctAnswer: 1,
      explanation: "長期的なキャリア形成には、専門性と人脈を計画的に築くことが重要です。",
      source: "F: セルフマネジメント - 研修59",
      difficulty: "intermediate",
    },
    {
      id: 100,
      question: "営業として成長し続けるために最も重要なことは？",
      options: [
        "常に高い売上目標を達成し続けること",
        "謙虚に学び続ける姿勢を持ち続けること",
        "業界でトップの営業になること",
        "後輩の育成に力を注ぐこと",
      ],
      correctAnswer: 1,
      explanation: "環境変化が激しい中、謙虚に学び続ける姿勢が長期的な成長と成果につながります。",
      source: "F: セルフマネジメント - 研修60",
      difficulty: "basic",
    },
  ],
}

// テストスコア計算関数
export function calculateFinalExamScore(
  answers: number[],
  exam: FinalExam
): {
  score: number
  percentage: number
  passed: boolean
  correctCount: number
  incorrectCount: number
} {
  let correctCount = 0
  for (let i = 0; i < exam.questions.length; i++) {
    if (answers[i] === exam.questions[i].correctAnswer) {
      correctCount++
    }
  }
  const percentage = Math.round((correctCount / exam.totalQuestions) * 100)
  return {
    score: correctCount,
    percentage,
    passed: percentage >= exam.passingScore,
    correctCount,
    incorrectCount: exam.totalQuestions - correctCount,
  }
}
